name: Deploy Flask App to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t toobamehboob/sugarcane:latest .
          docker push toobamehboob/sugarcane:latest

      # SSH into EC2 instance and run Docker container
      - name: Deploy to EC2
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}  # Store your private key in GitHub Secrets
        run: |
          # Decode the SSH private key and save it as a file
          echo $AWS_SSH_KEY | base64 --decode > C:\Users\acer\Downloads\tooab.pem
          
          # Set proper permissions for the private key
          chmod 600 /tmp/tooab.pem
          
          # SSH into EC2 and run Docker commands to pull and run the image
          ssh -i /tmp/tooab.pem ec2-user@ec2-3-84-62-176.compute-1.amazonaws.com \
            "docker pull toobamehboob/sugarcane:latest && \
             docker run -d -p 8080:8080 toobamehboob/sugarcane:latest"
